---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Template used during IAM module training. Exploring service access, first with unrestricted access and then with restricted access'
Resources:
  S3FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3AccessRole
      Description: IAM role with S3 Access
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::123456789012:user/generic.labs'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: S3ReadyOnlyLebowski
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: Statement1AllowUnrestrictedWrite
                Effect: Allow
                Action:
                  - s3:Put*
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket1, '/*']]
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket2, '/*']]
              - Sid: Statement2AllowRestrictedRead
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket1]]
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket1, '/*']]
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket2]]
                  - !Join ['', ['arn:aws:s3:::', !Ref s3Bucket2, '/*']]
                Condition:
                  StringLike:
                    s3:prefix:
                      - 'lebowski/'
  s3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: my-s3-bucket-1
      Tags:
        - Key: Owner
          Value: SomeUser
  s3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: my-s3-bucket-2
      Tags:
        - Key: Owner
          Value: SomeUser
Outputs:
  S3FullAccessRole:
    Description: 'ARN of role with S3 Full Access'
    Value: !GetAtt S3FullAccessRole.Arn
  S3Bucket1:
    Description: 'Name of s3 bucket 1'
    Value: !Ref s3Bucket1
  S3Bucket2:
    Description: 'Name of s3 bucket 2'
    Value: !Ref s3Bucket2
